#pragma once
#include <iostream>
#include <regex>
#include "src/lucky_or_unlucky/lucky_or_unlucky.hpp"
#include "src/cipher_ceaser/cipher.hpp"
#include "src/palindrome/palindrome.hpp"
#include "src/from_arab_to_roman/from_arab_to_roman.hpp"
#include "src/arithmetic_expression/arith_ex.hpp"
#include "src/play_with_path/pwp.hpp"
#include "src/string_substring/str_substr.hpp"
#include "src/repl_symb/repl.hpp"
#include "src/translit/translit.hpp"
#include "src/regex_searching/regex_searching.hpp"